/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ssd.auto.garage.app;

import ssd.auto.garage.list.LinkedList;

import static ssd.auto.garage.utilities.StringUtils.join;
import static ssd.auto.garage.utilities.StringUtils.split;
import static ssd.auto.garage.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
